version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
