version: '3.8'

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306

  express-app:
    build: .
    container_name: express-app
    restart: always
    depends_on:
      - mysqldb
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/app/src
